
from enum import Enum


class ObstacleLabel(str, Enum):
    """
    Label of the image on the obstacle.
    """
    A = "A"
    B = "B"
    C = "C"
    D = "D"
    E = "E"
    F = "F"
    G = "G"
    H = "H"
    S = "S"
    T = "T"
    U = "U"
    V = "V"
    W = "W"
    X = "X"
    Y = "Y"
    Z = "Z"
    Number_1 = "1"
    Number_2 = "2"
    Number_3 = "3"
    Number_4 = "4"
    Number_5 = "5"
    Number_6 = "6"
    Number_7 = "7"
    Number_8 = "8"
    Number_9 = "9"
    Shape_Bullseye = "BULLSEYE"
    Shape_Circle = "CIRCLE"
    Shape_Up = "UP"
    Shape_Down = "DOWN"
    Shape_Left = "LEFT"
    Shape_Right = "RIGHT"
    Unknown = "UNKNOWN"
